# ASSIGNMENT 1                - BY RAVINOOR (21104081),EE
# QUES 1

# CODE FOR QUESTION 1 (FINDING AVERAGE OF THREE NUMBERS ENTERED BY USERS)
print("WRITE YOUR NUMBERS.")
number1=float(input('TYPE NUMBER 1 \n'))
number2=float(input('TYPE NUMBER 2 \n'))
number3=float(input('TYPE NUMBER 3 \n'))
avg_= (number1+number2+number3)/3
print("THE AVERAGE OF YOUR NUMBERS IS", avg_)

# QUES 2

#CODE FOR QUESTION 2 ( COMPUTING A USER INCOME TAX )
print("FOLLOW TO FIND YOUR INCONE TAX")
TAX_RATE =20/100 #(20%)
STANDARD_DEDUCTION = 10000 #($)
DEPENDENT_DEDUCTION = 3000 #($)
GROSS_INCOME=float(input('ENTER YOUR GROSS INCOME TO IN "$"(TO NEAREST PENNY).\n'))
NO_OF_DEPENDENT =int(input('ENTER YOU NUMBER OF DEPENDENTS.\n'))
TAXABLE_INCOME=GROSS_INCOME-STANDARD_DEDUCTION-(DEPENDENT_DEDUCTION*NO_OF_DEPENDENT)
TAX=TAXABLE_INCOME*TAX_RATE
print("YOUR INCOME TAX IS $",TAX)

# QUES 3

# CODE FOR QUES 3 (PROGRAM FOR DIFFERENT DATA TYPES IN LIST)
print("LIST IS IN THE FORMAT OF [STUDENT ID,NAME,GENDER,COURSE NAME,CGPA]")
print("FOR GENDER (F-FEMALE),(M-MALE),(U-UNKOWN) ")
MY_LIST=[21104081,'RAVINOOR','M','EE',9.3]
print("MY LIST IS",MY_LIST)

# QUES 4

# CODE FOR QUES 4 (TAKING 5 STUDENT MARKS AND SORTING THEM)
print("ENTER THE MARKS OF STUDENTS B/W 1 TO 100")
STUDENT_1=float(input('ENTER MARKS OF STUDENT 1:'))
STUDENT_2=float(input('ENTER MARKS OF STUDENT 2:'))
STUDENT_3=float(input('ENTER MARKS OF STUDENT 3:'))
STUDENT_4=float(input('ENTER MARKS OF STUDENT 4:'))
STUDENT_5=float(input('ENTER MARKS OF STUDENT 5:'))
LIST=[STUDENT_1,STUDENT_2,STUDENT_3,STUDENT_4,STUDENT_5]
LIST.sort()
print("THE SORTED MARKS OF STUDENTS FROM INCREASING TO DECREASING ORDER IN A LIST ARE: \n",LIST)

# QUES 5
# (a)

# CODE FOR QUES 5 (a) (REMOVING AN ELEMENT FROM LIST)
LIST_PROVIDED=['RED','GREEN','WHITE','BLACK','PINK','YELLOW']
print("THE LIST GIVEN IS :",LIST_PROVIDED)
LIST_PROVIDED.remove('BLACK') # TO REMOVE THE 4TH ELEMENT
print("THE UPDATED LIST IS AFTER REMOVING 4TH ELEMENT IS \n",LIST_PROVIDED)

# (b)

# THE CODE FOR QUES 5 (b) (REPLACING BLACK, PINK WITH PURPLE)
LIST_PROVIDED_=['RED','GREEN','WHITE','BLACK','PINK','YELLOW']
print("THE LIST GIVEN IS :",LIST_PROVIDED_)
LIST_PROVIDED_[3:5]=['PURPLE']
print("THE UPDATED LIST IS AFTER REPLACING BLACK,PINK WITH PURPLE IS \n",LIST_PROVIDED_)


#ASSIGNMENT COMPLETED          - BY RAVINOOR(21104081),EE