# ANSWER 1
"""
WRITE YOUR NUMBERS.
TYPE NUMBER 1
65
TYPE NUMBER 2
45
TYPE NUMBER 3
36
THE AVERAGE OF YOUR NUMBERS IS 48.666666666666664

Process finished with exit code 0
"""
# ANSWER 2
"""
FOLLOW TO FIND YOUR INCONE TAX
ENTER YOUR GROSS INCOME TO IN "$"(TO NEAREST PENNY).
50000.0
ENTER YOU NUMBER OF DEPENDENTS.
5
YOUR INCOME TAX IS $ 5000.0

Process finished with exit code 0
"""
# ANSWER 3
"""
LIST IS IN THE FORMAT OF [STUDENT ID,NAME,GENDER,COURSE NAME,CGPA]
FOR GENDER (F-FEMALE),(M-MALE),(U-UNKOWN) 
MY LIST IS [21104081, 'RAVINOOR', 'M', 'EE', 9.3]

Process finished with exit code 0
"""
# ANSWER 4
"""
ENTER THE MARKS OF STUDENTS B/W 1 TO 100
ENTER MARKS OF STUDENT 1:80
ENTER MARKS OF STUDENT 2:42
ENTER MARKS OF STUDENT 3:33
ENTER MARKS OF STUDENT 4:95
ENTER MARKS OF STUDENT 5:56
THE SORTED MARKS OF STUDENTS FROM INCREASING TO DECREASING ORDER IN A LIST ARE: 
 [33.0, 42.0, 56.0, 80.0, 95.0]

Process finished with exit code 0
"""
# ANSWER 5
# (A)
"""
THE LIST GIVEN IS : ['RED', 'GREEN', 'WHITE', 'BLACK', 'PINK', 'YELLOW']
THE UPDATED LIST IS AFTER REMOVING 4TH ELEMENT IS 
 ['RED', 'GREEN', 'WHITE', 'PINK', 'YELLOW']

Process finished with exit code 0
"""
# (B)
"""
THE LIST GIVEN IS : ['RED', 'GREEN', 'WHITE', 'BLACK', 'PINK', 'YELLOW']
THE UPDATED LIST IS AFTER REPLACING BLACK,PINK WITH PURPLE IS 
 ['RED', 'GREEN', 'WHITE', 'PURPLE', 'YELLOW']

Process finished with exit code 0
"""